### ISSUE TITLE
summit discovery server

### ISSUE THREAD

**Issue by onorzq** [onorzq/dist-sys-exercises#1]

**Comment by wenhuizhang** [comment]
Hi, dont quite understand which protocol you are following: 

wenhui-2:discovery WenhuiZhang$ telnet 127.0.0.1 1111
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
lookup g b 
Connection closed by foreign host.
wenhui-2:discovery WenhuiZhang$ telnet 127.0.0.1 1111
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
add b g 1 2
Connection closed by foreign host.
wenhui-2:discovery WenhuiZhang$ telnet 127.0.0.1 1111
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
add b g 1 3
Connection closed by foreign host.
wenhui-2:discovery WenhuiZhang$ telnet 127.0.0.1 1111
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
add b g 1 2
Connection closed by foreign host.
wenhui-2:discovery WenhuiZhang$ telnet 127.0.0.1 1111
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
lookup b g 
Connection closed by foreign host.

Accepted connection from client
add b g 1 2

Accepted connection from client
lookup b g 
java.net.NoRouteToHostException: No route to host
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at java.net.Socket.<init>(Socket.java:434)
    at java.net.Socket.<init>(Socket.java:211)
    at DisServer.process(DisServer.java:76)
    at DisServer.start(DisServer.java:20)
    at DisServer.main(DisServer.java:129)
ghave shuted down
Exception in thread "main" java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:886)
    at java.util.ArrayList$Itr.next(ArrayList.java:836)
    at DisServer.process(DisServer.java:71)
    at DisServer.start(DisServer.java:20)
    at DisServer.main(DisServer.java:129)
